/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author kishanbhakta
 */
public class Startup_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Startup_Frame
     */
    public Startup_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
Alcohol_Page ap = new Alcohol_Page();
Drugs_Page dp = new Drugs_Page();
Meds_Page mp = new Meds_Page();
Score_Page sp = new Score_Page();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Alcohol_Button = new javax.swing.JButton();
        Drugs_Button = new javax.swing.JButton();
        Meds_Button = new javax.swing.JButton();
        Score_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Please select one of the following:");

        Alcohol_Button.setText("Alcohol");
        Alcohol_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alcohol_ButtonActionPerformed(evt);
            }
        });

        Drugs_Button.setText("Drug");
        Drugs_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Drugs_ButtonActionPerformed(evt);
            }
        });

        Meds_Button.setText("Meds");
        Meds_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meds_ButtonActionPerformed(evt);
            }
        });

        Score_Button.setText("Score");
        Score_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Score_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Meds_Button)
                    .addComponent(Alcohol_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Drugs_Button)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Score_Button)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alcohol_Button)
                    .addComponent(Drugs_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Meds_Button)
                    .addComponent(Score_Button))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Alcohol_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alcohol_ButtonActionPerformed
        // TODO add your handling code here:
        dp.setVisible(false);
        mp.setVisible(false);
        sp.setVisible(false);
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Alcohol_ButtonActionPerformed

    private void Drugs_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Drugs_ButtonActionPerformed
        // TODO add your handling code here:
        ap.setVisible(false);
        mp.setVisible(false);
        sp.setVisible(false);
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Drugs_ButtonActionPerformed

    private void Meds_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meds_ButtonActionPerformed
        // TODO add your handling code here:
        ap.setVisible(false);
        dp.setVisible(false);
        sp.setVisible(false);
        mp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Meds_ButtonActionPerformed

    private void Score_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Score_ButtonActionPerformed
        // TODO add your handling code here:
        ap.setVisible(false);
        mp.setVisible(false);
        dp.setVisible(false);
        sp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Score_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Startup_Frame sf = new Startup_Frame();
                sf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alcohol_Button;
    private javax.swing.JButton Drugs_Button;
    private javax.swing.JButton Meds_Button;
    private javax.swing.JButton Score_Button;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}